name: CI Pipeline

on:
  pull_request:
    branches:
      - main  # Runs the workflow when a PR is created to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (if applicable)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install  # Change this based on your project (e.g., yarn install, pip install)

      - name: Run build
        run: npm run build  # Adjust this to match your build command

      - name: Run tests (optional)
        run: npm test  # Run tests if applicable
