name: CI Pipeline

on:
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up ASP .Net 
        uses: actions/setup-node@v3
        with:
          node-version: '9.0'

      - name: Install dependencies
        run: npm install  

      - name: Run build
        run: npm run build  

      - name: Run tests (optional)
        run: npm test  
